### ISSUE TITLE
Split to cgal-bindings

### ISSUE THREAD

**Issue by edisongustavo** [conda-forge/cgal-feedstock#10]
I noticed that this package also includes the python bindings.

I would prefer that this package doesn't depend on python, being only C++.
We could add another recipe (cgal-bindings) specifically for that.

What do you think?

**Comment by xantares** [comment]
It's simpler for me to maintain just one package.
For now no package only depends on the c++ lib.

**Comment by edisongustavo** [comment]
Ok.

I just couldn't make the bindings compile on windows, lots of compilations errors happen, so I will skip them.

**Comment by xantares** [comment]
do you have logs ? I'm curious to see why it's not possible.
