### ISSUE TITLE
MPFR supports only MSVC 2015

### ISSUE THREAD

**Issue by isuruf** [conda-forge/cgal-feedstock#16]
In the py34 build, MPFR package built with vc14 is used whereas all the other dependencies are from vc10. Mixing vc runtimes is not generally a good idea.

**Comment by xantares** [comment]
what do you propose, have different mpfr builds ?

**Comment by isuruf** [comment]
There are 2 options,
1. Drop py34 build.
2. Somehow support building MPFR with vc10.
