### ISSUE TITLE
Problematic CMake modules inside CGAL 4.12 packages

### ISSUE THREAD

**Issue by tadeu** [conda-forge/cgal-feedstock#39]
I've noticed that both in the `win-64` and in the `linux-64` CGAL 4.12 packages, there are a lot of extra CMake modules that are not needed, and that are messing with CMake.

In the `win-64` package, these are located in `Library\lib\cmake\CGAL`; in the `linux-64` package, these are located in `lib/cmake/CGAL`. There are a bunch of `FindModule.cmake` files for many common libraries, for example, there is a `FindGLEW.cmake` that seems to be from 2009 and that do not define `Glew::Glew` (as the standard `FindGLEW.cmake` from CMake itself defines). This is causing trouble for CMake, I don't know exactly why, but when the CMake package is installed, it is preferring these Find modules to the standard ones.

My first proposal is to patch the recipe to just remove these files after building CGAL (remove all `Find*.cmake`, as CGAL seems to rely on `CGALConfig.cmake`).

NOTE: the files were already present in CGAL 4.11, but they were in `lib/CGAL` in `linux-64` and in `Library\lib\CGAL` in `win-64`. The problem is that now they are a subdirectory of the standard place where CMake look for its modules (`.../lib/cmake`).  Another solution would be to move these files again.

**Comment by xantares** [comment]
Please open an issue upstream first to see what they think.

**Comment by tadeu** [comment]
Opened https://github.com/CGAL/cgal/issues/3317

**Comment by tadeu** [comment]
I believe they will fix this issue in the next CGAL release, so if nobody else has stumbled on this problem, I think we can wait for that.
