### ISSUE TITLE
Python 3.7 version

### ISSUE THREAD

**Issue by ostrokach** [conda-forge/cgal-feedstock#42]
What would be the process for getting `cgal` binaries built for Python 3.7?

I notice that most of the packages on `conda-forge` already have Python 3.7 binaries, but `cgal` is still Python<=3.6.

Sorry if this is not the right place to ask.

**Comment by sodre** [comment]
It is PR #41 that is pending for 3.7

**Comment by tadeu** [comment]
Fixed by merging #41 unless you need a macOS version, in this case, wait for #46
