### ISSUE TITLE
MSVC build libs have suffix

### ISSUE THREAD

**Issue by wolfv** [conda-forge/cgal-feedstock#53]
On Windows, the libraries have a suffix of the form: `-vc140-mt-4.14.1.lib`.
I am unsure if this is intentional?

I think it would be nice if it was shipped without the suffix.

**Comment by tadeu** [comment]
This was the output from a standard CGAL build, so it seems ok (as long as CMake is able to find the coorect libs). But note that this is from the `cgal-cpp` package, and newer versions don't include libs anymore (`cgal-cpp` became a header-only package)
