### ISSUE TITLE
Windows CGAL package doesn't install mpir.dll

### ISSUE THREAD

**Issue by timmclennan** [conda-forge/cgal-feedstock#63]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I created an environment on Windows with the latest versions of cgal (5.0.1) and python 3.7. 
The CGAL extension modules wouldn't load into any python consoles / notebooks. eg:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-fe778a927dac> in <module>
----> 1 from CGAL import CGAL_Kernel

C:\software\Anaconda\envs\cgal\lib\site-packages\CGAL\CGAL_Kernel.py in <module>
     13 # Import the low-level C/C++ module
     14 if __package__ or "." in __name__:
---> 15     from . import _CGAL_Kernel
     16 else:
     17     import _CGAL_Kernel

ImportError: DLL load failed: The specified module could not be found.
````
Looking at the dependencies, the dll for this module at least has one on the dll (mpir.dll) for the MPIR library (https://mpir.org/)

I had another environment which contained that dll in the `Library/bin` directory and copying it appeared to allow the modules to load.

Installing the `mpir` conda package also fixed the issue, so I suppose it's a dependency issue with either this package or the `cgal-cpp` package.

<br/>
Environment (<code>conda list</code>):
<details>
<code>
# packages in environment at C:\software\Anaconda\envs\cgal:
#
# Name                    Version                   Build  Channel
# packages in environment at C:\software\Anaconda\envs\cgal:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py37h2bbff1b_1  
async_generator           1.10             py37h28b3542_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
boost-cpp                 1.72.0               h54f0996_4    conda-forge
bzip2                     1.0.8                he774522_0  
ca-certificates           2021.1.19            haa95532_1  
certifi                   2020.12.5        py37haa95532_0  
cffi                      1.14.5           py37hcd4344a_0  
cgal                      5.0.1            py37h89887c2_2    conda-forge
cgal-cpp                  5.0.1                h26c6e29_1    conda-forge
colorama                  0.4.4              pyhd3eb1b0_0  
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
eigen                     3.3.7                h74a9793_0  
entrypoints               0.3                      py37_0  
icu                       58.2                 ha925a31_3  
importlib-metadata        3.7.3            py37haa95532_1  
importlib_metadata        3.7.3                hd3eb1b0_1  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.22.0           py37h7813e69_0    conda-forge
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
jedi                      0.18.0           py37haa95532_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
jpeg                      9b                   hb83a4c4_2  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py37haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
libpng                    1.6.37               h2a8f88b_0  
libsodium                 1.0.18               h62dcd97_0  
lz4-c                     1.9.3                h2bbff1b_0  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markupsafe                1.1.1            py37hfa6e2cd_1  
mistune                   0.8.4           py37hfa6e2cd_1001  
mkl                       2020.2                      256  
mkl-service               2.3.0            py37h196d8e1_0  
mkl_fft                   1.3.0            py37h46781fe_0  
mkl_random                1.1.1            py37h47e9c7a_0  
mpfr                      4.0.2                h62dcd97_1  
msys2-conda-epoch         20160418                      1  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
notebook                  6.3.0            py37haa95532_0  
numpy                     1.19.2           py37hadc3359_0  
numpy-base                1.19.2           py37ha3acd2a_0  
openssl                   1.1.1k               h2bbff1b_0  
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.3            py37hf11a4ad_0  
pandoc                    2.12                 haa95532_0  
pandocfilters             1.4.3            py37haa95532_1  
parso                     0.8.1              pyhd3eb1b0_0  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       21.0.1           py37haa95532_0  
prometheus_client         0.9.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
prompt_toolkit            3.0.17               hd3eb1b0_0  
pycparser                 2.20                       py_2  
pygments                  2.8.1              pyhd3eb1b0_0  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py37h6538335_2  
pyrsistent                0.17.3           py37he774522_0  
python                    3.7.10               h6244533_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
pywin32                   227              py37he774522_1  
pywinpty                  0.5.7                    py37_0  
pyzmq                     20.0.0           py37hd77b12b_1  
qt                        5.9.7            vc14h73c81de_0  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py37haa95532_0  
sip                       4.19.8           py37h6538335_0  
six                       1.15.0           py37haa95532_0  
sqlite                    3.35.2               h2bbff1b_0  
terminado                 0.9.3            py37haa95532_0  
testpath                  0.4.4              pyhd3eb1b0_0  
tornado                   6.1              py37h2bbff1b_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
typing_extensions         3.7.4.3            pyha847dfd_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py37_0  
wincertstore              0.2                      py37_0  
winpty                    0.4.3                         4  
xz                        5.2.5                h62dcd97_0  
zeromq                    4.3.3                ha925a31_3  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h62dcd97_4  
zstd                      1.4.5                h04227a9_0 

</code>
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : cgal
    active env location : C:\software\Anaconda\envs\cgal
            shell level : 2
       user config file : C:\Users\tim.mclennan\.condarc
 populated config files : C:\Users\tim.mclennan\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=11.0
       base environment : C:\software\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\software\Anaconda\pkgs
                          C:\Users\tim.mclennan\.conda\pkgs
                          C:\Users\tim.mclennan\AppData\Local\conda\conda\pkgs
       envs directories : C:\software\Anaconda\envs
                          C:\Users\tim.mclennan\.conda\envs
                          C:\Users\tim.mclennan\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

**Comment by tadeu** [comment]
@timmclennan, `mpir` is already declared as a dependency of `mpfr` in conda-forge, the problem you are having is probably because of mixing up with Anaconda packages (`mpfr` from Anaconda does not declare `mpir` as a dependency).  The `conda list` you posted didn't show channel information, though.  It's usually better to use `conda-forge` as the first channel so that its packages will be preferred.

**Comment by tadeu** [comment]
If you still have the same problem when using packages from conda-forge only, feel free to post more information here, I'll reopen it 👍
